import { Gift, Present } from './../../../autogenerated/back-map';
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-gift-resume',
  templateUrl: './gift-resume.component.html',
  styleUrl: './gift-resume.component.scss'
})
export class GiftResumeComponent {

  @Input()
  public present?: Present;

  @Input()
  public gift: Gift = {};

  get value(): number | undefined {
    return this.present?.value;
  }

  get total(): number | undefined {
    return this.present?.value;
  }

}
