import { ModalService } from './../../../component/modal/modal.service';
import { MODAL_DATA, ModalComponent } from '../../../component/modal/modal.component';
import { Gift, Present } from './../../../autogenerated/back-map';
import { Component, Inject, Input } from '@angular/core';
import { MessageBoxType } from '../../../component/message-box/message-box.component';

@Component({
  selector: 'app-gift-resume',
  templateUrl: './gift-resume.component.html',
  styleUrl: './gift-resume.component.scss'
})
export class GiftResumeComponent {

  @Input()
  public gift: Gift = {};

  get value(): number | undefined {
    return this.gift?.present?.value;
  }

  get total(): number | undefined {
    return this.gift?.present?.value;
  }

  constructor(
    private ModalService: ModalService,
    private modalRef: ModalComponent,
    @Inject(MODAL_DATA) private data: any,
  ) {
    this.gift.present = data.present;
  }

  close() {
    this.modalRef.close();
  }

  pay() {
    if (!this.gift.name) {
      this.ModalService.openMessageBox({
        message: "Informe seu nome",
        type: MessageBoxType.WARNING
      });
      return;
    }

    this.modalRef.close(this.gift);
  }

}
