import { Component, ViewChild } from '@angular/core';
import { Gift, Present } from '../../autogenerated/back-map';
import { WeddingService } from '../../service/wedding.service';
import { ModalDirective } from '../../directive/modal.directive';
import { MercadoPagoCheckoutProComponent } from '../../component/mercado-pago-checkout-pro/mercado-pago-checkout-pro.component';

@Component({
  selector: 'app-gifts',
  templateUrl: './gifts.component.html',
  styleUrl: './gifts.component.scss'
})
export class GiftsComponent {

  @ViewChild('modalResume') modalResume?: ModalDirective;
  @ViewChild('modalPayment') modalPayment?: ModalDirective;
  @ViewChild('mercadopago') mercadopago?: MercadoPagoCheckoutProComponent;

  presents: Present[] = [];

  selectedPresent?: Present;
  gift: Gift = {};

  constructor(
    private weddingService: WeddingService
  ) { }

  ngOnInit(): void {
    this.weddingService.getAllAvailableGifts().subscribe(presents => {
      this.presents = presents;
    })
  }

  openResume(selectedPresent: Present) {
    this.selectedPresent = selectedPresent;
    this.modalResume?.open();
  }

  closeResume() {
    this.modalResume?.close();
  }

  payment() {
    this.modalResume?.close();
    if (this.selectedPresent) {
      this.gift.present = this.selectedPresent;
      this.weddingService.gift(this.gift).subscribe(response => {
        if (response.preferenceId) {
          this.modalPayment?.open();
          this.mercadopago?.init(response.preferenceId);
        }
      });
    }
  }

}
