import { Confirmation } from './../../autogenerated/back-map/model/confirmation';
import { MessageBoxType } from '../../component/message-box/message-box.component';
import { ModalService } from '../../component/modal/modal.service';
import { WeddingService } from '../../service/wedding.service';
import { Component } from '@angular/core';

const MAX_ADULT = 5;
const MAX_CHILD = 10;

const initArray = function (arrayQuantity: number, start_from: number) {
  return Array(arrayQuantity).fill(undefined).map((x, i) => i + start_from);
}

@Component({
  selector: 'app-confirmation',
  templateUrl: './confirmation.component.html',
  styleUrl: './confirmation.component.scss'
})
export class ConfirmationComponent {

  adultItens = initArray(MAX_ADULT, 1);
  childItens = initArray(MAX_CHILD, 0);

  confirmation!: Confirmation;

  adultQuantity!: number;
  childQuantity!: number;

  constructor(
    private weddingService: WeddingService,
    private modalService: ModalService,
  ) {
    this.zerarTela();
  }

  sendClick(): void {
    if (!this.confirmation)
      return;
    
    this.confirmation.adultsNames = this.confirmation?.adultsNames?.filter((x, i) => i < this.adultQuantity - 1); //-1 para excluir ele mesmo
    this.confirmation.childrenNames = this.confirmation?.childrenNames?.filter((x, i) => i < this.childQuantity);

    this.weddingService.confirmInvite(this.confirmation).subscribe({
      complete: () => {
        this.modalService.openMessageBox({
          title: "Confirmação enviada",
          message: "Obrigado por enviar a sua confirmação de presença e fazer parte desse dia tão especial para nós",
          type: MessageBoxType.SUCCESS
        });
        this.zerarTela();
      }
    });
  }

  initNewArray(arrayQuantity: number, start_from: number) {
    return initArray(arrayQuantity, start_from);
  }

  zerarTela() {
    this.adultQuantity = 1;
    this.childQuantity = 0;
    this.confirmation = {
      adultsNames: [],
      childrenNames: [],
    }
  }

  stringfy(obj: any) {
    return JSON.stringify(obj);
  }

}
