import { Confirmation } from './../autogenerated/back-map/model/confirmation';
import { Injectable } from '@angular/core';
import { GiftControllerService } from '../autogenerated/back-map/api/giftController.service';
import { Observable } from 'rxjs';
import { Gift } from '../autogenerated/back-map/model/gift';
import { ConfirmationControllerService } from '../autogenerated/back-map';

@Injectable({
  providedIn: 'root'
})
export class WeddingService {

  constructor(
    private giftControllerService: GiftControllerService,
    private confirmationControllerService: ConfirmationControllerService
  ) { }

  getAllAvailableGifts(): Observable<Gift[]> {
    return this.giftControllerService.getAllAvailable();
  }

  confirmInvite(confirmation: Confirmation): Observable<void> {
    return this.confirmationControllerService.confirm(confirmation);
  }
}
