import { Injectable } from '@angular/core';
import { GiftControllerService } from '../autogenerated/back-map/api/giftController.service';
import { Observable } from 'rxjs';
import { Gift } from '../autogenerated/back-map/model/gift';

@Injectable({
  providedIn: 'root'
})
export class WeddingService {

  constructor(
    private giftControllerService: GiftControllerService
  ) { }

  getAllAvailableGifts(): Observable<Gift[]> {
    return this.giftControllerService.getAllAvailable();
  }
}
