import { Confirmation } from './../autogenerated/back-map/model/confirmation';
import { GiftControllerService, ConfirmationControllerService } from './../autogenerated/back-map/api/api';
import { Gift, GiftResponse } from './../autogenerated/back-map/model/models';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class WeddingService {

  constructor(
    private giftControllerService: GiftControllerService,
    private confirmationControllerService: ConfirmationControllerService
  ) { }

  getAllAvailableGifts(): Observable<Gift[]> {
    return this.giftControllerService.getAllAvailable();
  }

  confirmInvite(confirmation: Confirmation): Observable<void> {
    return this.confirmationControllerService.confirm(confirmation);
  }

  gift(gift: Gift): Observable<GiftResponse> {
    return this.giftControllerService.gift(gift);
  }
}
